service: cw-logs-upload

frameworkVersion: '3'

custom:
  version: v1
  stage: ${sls:stage}
  localMountPath: /mnt/efs
  efs_access_point_arn: ${ssm:/cwlogs/efs/efs_access_point_arn}

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-south-1
  profile: personal

  environment:
    stage: ${self:custom.stage}

  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/AmazonElasticFileSystemClientFullAccess
      statements:
        - Effect: Allow
          Action:
            - logs:FilterLogEvents
          Resource:
            - 'arn:aws:logs:eu-south-1:745049313685:log-group:/aws/lambda/cw-logs-upload-dev-cwLogsWorker:*'

package:
  patterns:
    - '!.git/**'
    - '!node_modules/**'
    - '!.terraform/**'
    - '!*.tf'

functions:
  cwLogsWorker:
    handler: ./src/workers/cw_logs_worker.handler
    events:
      - schedule: rate(1 day)
  fileWrite:
    handler: ./src/workers/file_write_worker.handler
    fileSystemConfig:
      localMountPath: ${self:custom.localMountPath}
      arn: ${self:custom.efs_access_point_arn}
    vpc:
      securityGroupIds:
        - sg-cf39e3a4
      subnetIds:
        - subnet-5b14f732
        - subnet-6c181514
        - subnet-fd99b5b7
  fileRead:
    handler: ./src/workers/file_read_worker.handler
    fileSystemConfig:
      localMountPath: ${self:custom.localMountPath}
      arn: ${self:custom.efs_access_point_arn}
    vpc:
      securityGroupIds:
        - sg-cf39e3a4
      subnetIds:
        - subnet-5b14f732
        - subnet-6c181514
        - subnet-fd99b5b7
